name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "xn--lbr3ii29c.xn--4gqz72a4nrtny.us.kg"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "65268f9083ad41e896df7e1b8cd8fe1e"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://xn--lbr3ii29c.xn--4gqz72a4nrtny.us.kg"

# url to repo, displayed in the index page
REPO = "https://github.com/yyyr-otz/pastebin-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "yyyr"

# the email displayed in TOS
TOS_MAIL = "pbxn--lbr3ii29c.xn--4gqz72a4nrtny.us.kg@"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
